<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="106" started-at="2017-06-29T09:33:02Z" finished-at="2017-06-29T09:33:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106" started-at="2017-06-29T09:33:02Z" finished-at="2017-06-29T09:33:03Z">
      <class name="TestBoardModel">
        <test-method status="PASS" signature="f()[pri:0, instance:TestBoardModel@1810399e]" name="f" duration-ms="2" started-at="2017-06-29T15:03:03Z" finished-at="2017-06-29T15:03:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- TestBoardModel -->
      <class name="TestBoard">
        <test-method status="PASS" signature="load_the_Board()[pri:0, instance:TestBoard@5f375618]" name="load_the_Board" is-config="true" duration-ms="28" started-at="2017-06-29T15:03:02Z" finished-at="2017-06-29T15:03:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- load_the_Board -->
        <test-method status="PASS" signature="adding_a_player()[pri:0, instance:TestBoard@5f375618]" name="adding_a_player" duration-ms="17" started-at="2017-06-29T15:03:03Z" finished-at="2017-06-29T15:03:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adding_a_player -->
        <test-method status="FAIL" signature="adding_new_player_should_throw_AlreadyPlayerExistsExcetion()[pri:0, instance:TestBoard@5f375618]" name="adding_new_player_should_throw_AlreadyPlayerExistsExcetion" duration-ms="2" started-at="2017-06-29T15:03:03Z" finished-at="2017-06-29T15:03:03Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'RISHABH' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'RISHABH' already exists on board
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:76)
	at TestBoard.adding_new_player_should_throw_AlreadyPlayerExistsExcetion(TestBoard.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adding_new_player_should_throw_AlreadyPlayerExistsExcetion -->
        <test-method status="FAIL" signature="adding_new_player_should_throw_MaxPlayersReachedExeption()[pri:0, instance:TestBoard@5f375618]" name="adding_new_player_should_throw_MaxPlayersReachedExeption" duration-ms="16" started-at="2017-06-29T15:03:03Z" finished-at="2017-06-29T15:03:03Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:71)
	at TestBoard.adding_new_player_should_throw_MaxPlayersReachedExeption(TestBoard.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adding_new_player_should_throw_MaxPlayersReachedExeption -->
        <test-method status="PASS" signature="deleting_the_player_removes_player()[pri:0, instance:TestBoard@5f375618]" name="deleting_the_player_removes_player" duration-ms="7" started-at="2017-06-29T15:03:03Z" finished-at="2017-06-29T15:03:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleting_the_player_removes_player -->
        <test-method status="FAIL" signature="deleting_the_player_throws_NoUserWithSuchUUIDException()[pri:0, instance:TestBoard@5f375618]" name="deleting_the_player_throws_NoUserWithSuchUUIDException" duration-ms="1" started-at="2017-06-29T15:03:03Z" finished-at="2017-06-29T15:03:03Z">
          <exception class="com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException">
            <message>
              <![CDATA[No Player with uuid '0d8a0022-ee81-45a3-a392-d51b3f1af3d8' on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException: No Player with uuid '0d8a0022-ee81-45a3-a392-d51b3f1af3d8' on board
	at com.qainfotech.tap.training.snl.api.Board.deletePlayer(Board.java:116)
	at TestBoard.deleting_the_player_throws_NoUserWithSuchUUIDException(TestBoard.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleting_the_player_throws_NoUserWithSuchUUIDException -->
      </class> <!-- TestBoard -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
